USE [TEST]

CREATE TABLE Wydawnictwo(
Wydawnictwo_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Nazwa VARCHAR(255) NOT NULL,
Data_zalozenia DATE NOT NULL);

CREATE TABLE Gatunek(
Gatunek_ID_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Nazwa VARCHAR(255) NOT NULL);

CREATE TABLE Status_ksiazki(
ID_status INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Info_status VARCHAR(20) NOT NULL);

CREATE TABLE Autor(
ID_autor INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Imie_autor VARCHAR(50) NOT NULL,
Nazwisko_autor VARCHAR(100) NOT NULL,
Kraj_pochodzenia VARCHAR(200));

CREATE TABLE Plec(
ID_plec INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Rodzaj VARCHAR(1) NOT NULL);
--(M mezczyzna, K kobieta)


CREATE TABLE Rola(
ID_rola INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Nazwa_roli VARCHAR(100) NOT NULL);


CREATE TABLE Adres(
ID_adres INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Kraj VARCHAR(255) NOT NULL,
Miejscowosc VARCHAR(255) NOT NULL,
Kod_pocztowy VARCHAR(6) NOT NULL,
Ulica VARCHAR(255) NOT NULL,
Numer_ulicy Varchar(10) NOT NULL,
Numer_lokalu VARCHAR(10));




CREATE TABLE Ksiazka(
ID_ksiazka INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Tytul VARCHAR(255) NOT NULL,
Rok_wydania DATE NOT NULL,
FK_ID_wydawnictwo INT NOT NULL FOREIGN KEY REFERENCES Wydawnictwo(Wydawnictwo_ID),
Data_zakupu DATE NOT NULL,
Gatunek VARCHAR(255) NOT NULL,
Liczba_stron INT NOT NULL,
Liczba_sztuk INT NOT NULL,
Cena DECIMAL NOT NULL,
Opis TEXT NOT NULL,
FK_ID_status INT NOT NULL FOREIGN KEY REFERENCES Status_ksiazki(ID_status));


CREATE TABLE Ksiazka_autor(
ID_ksiazka_autor INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FK_ID_autor INT NOT NULL FOREIGN KEY REFERENCES Autor(ID_autor),
FK_ID_ksiazka INT NOT NULL FOREIGN KEY REFERENCES Ksiazka(ID_ksiazka));




CREATE TABLE Uzytkownik(
ID_uzytkownik INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
imie VARCHAR(100) NOT NULL,
nazwisko VARCHAR(200) NOT NULL,
FK_ID_plec INT NOT NULL FOREIGN KEY REFERENCES Plec(Id_plec),
Data_urodzenia DATE NOT NULL,
PESEL VARCHAR(11) UNIQUE NOT NULL,
Numer_telefonu VARCHAR(9) NOT NULL,
Login_uzytkownika VARCHAR(100) UNIQUE NOT NULL,
Haslo VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE CHECK (email LIKE '%_@_%._%'),
FK_ID_rola INT NOT NULL FOREIGN KEY REFERENCES Rola(ID_Rola),
FK_ID_adres INT NOT NULL FOREIGN KEY REFERENCES Adres(ID_Adres),
Czy_zapomniany BIT NOT NULL DEFAULT 0 -- Domyœlnie uzytkownik jest nieaktywny (0).
);

CREATE TABLE Rejestracja(
ID_Rejestr INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FK_ID_ksiazka INT NOT NULL FOREIGN KEY REFERENCES Ksiazka(ID_ksiazka),
FK_ID_uzytkownik INT NOT NULL FOREIGN KEY REFERENCES Uzytkownik(ID_Uzytkownik),
Data_Rejestracji DATETIME NOT NULL DEFAULT GETDATE());


CREATE TABLE Zapominany(
ID_zapominany INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FK_ID_uzytkownik INT NOT NULL FOREIGN KEY REFERENCES Uzytkownik(ID_Uzytkownik),
Data_zapomnienia DATETIME NOT NULL DEFAULT GETDATE(),
Zglaszacz INT NOT NULL FOREIGN KEY REFERENCES Uzytkownik(ID_Uzytkownik));
